import '../globals.css';
import { DashboardLayout } from '@/components/templates/Dashboard';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Epilogue } from 'next/font/google';
import { redirect } from 'next/navigation';
import authOptions from '../api/auth/[...nextauth]/options';
import NextAuthProvider from '@/context/NextAuthProvider';

const epilogue = Epilogue({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await getServerSession(authOptions);
  if (session === null) {
    return redirect('/signin');
  }
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={epilogue.className}>
        <main>
          <NextAuthProvider>
            <DashboardLayout>{children}</DashboardLayout>
          </NextAuthProvider>
        </main>
      </body>
    </html>
  );
}
