import '../globals.css';
import { DashboardLayout } from '@/components/templates/Dashboard';
import type { Metadata } from 'next';
import { Epilogue } from 'next/font/google';

const epilogue = Epilogue({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={epilogue.className}>
        <main>
          <DashboardLayout>{children}</DashboardLayout>
        </main>
      </body>
    </html>
  );
}
